DROP DATABASE IF EXISTS TRACKRdb;
CREATE DATABASE TRACKRdb;

USE TRACKRdb;

CREATE TABLE Daily_Summary(
ID INT NOT NULL AUTO_INCREMENT,
Food VARCHAR (50) NOT NULL,
Calories INT NULL,
Carbohydrates DECIMAL(5,2),
Fat DECIMAL(5,2),
Protein DECIMAL(5,2),
PRIMARY KEY (ID)
);



